sudo: required
before_install:
- sudo apt-get -qq update
- sudo apt-get install texlive texlive-latex3
script:
<<<<<<< HEAD
- ./build.sh
deploy:
  provider: script
  script: ./travis_deploy.sh
  skip_cleanup: true
  on:
    branch: master
=======
- pdflatex -interaction=errorstopmode -halt-on-error Paper.tex
- bibtex Paper
- pdflatex -interaction=errorstopmode -halt-on-error Paper.tex
- pdflatex -interaction=errorstopmode -halt-on-error Paper.tex
- pdflatex -interaction=errorstopmode -halt-on-error Paper.tex
deploy:
  provider: script
  script: travis_deploy.sh
  skip_cleanup: true
  on:
    branch: deploytest
>>>>>>> Deploy pdf from travis.
env:
  global:
    - ENCRYPTION_LABEL="19a81de38b62"
    - COMMIT_AUTHOR_EMAIL="chris@ethereum.org"
    - COMMIT_AUTHOR="Travis CI"
<<<<<<< HEAD
    - PUSH_REPO="git@github.com:ethereum/yellowpaper.git"
=======
    - PUSH_REPO="git@github.com:ethereum/yellowpaper.git"
>>>>>>> Deploy pdf from travis.
